### ISSUE TITLE
Foobar example - Can't stop the service

### ISSUE THREAD

**Issue by DominicD** [Devolutions/ceviche-rs#22]
Hi I hope its okay I create another Issue for this. 

I just compiled and tried your foobar example. 
So I tried to create the service, start it and then stop it and delete it.
However as you can see in the screenshot below it can not stop it. 
Also the delete fails, however if I afterwards stop the service manually in Windows it is deleted immediatly after its stopped.

![grafik](https://user-images.githubusercontent.com/7666187/95759016-782aa880-0ca9-11eb-9196-8d9fb011394e.png)

It is built in debug mode with rustc 1.47.0 and windows-msvc toolchain.

**Comment by thenextman** [comment]
Hi Dominic

This is a long-standing annoyance that we haven't addressed because we normally just call the service manager directly on Windows (`net stop foobar`, `net start foobar`)

However, I've gone ahead and committed a fix for this and published version 0.4.2. 

Please give it a try.

**Comment by DominicD** [comment]
Hi Thank you! 
I can confirm it works now.
